language: perl

perl:
 - "5.10"
 - "5.12"
 - "5.14"
 - "5.16"

install:
 - sudo apt-get install libffi-dev
 - cpanm Dist::Zilla Dist::Zilla::PluginBundle::Author::ALEXBIO Devel::CheckLib
 - dzil listdeps --missing | cpanm

script:
 - dzil test

notifications:
  recipient:
   - alessandro@ghedini.me
  email:
    on_success: change
    on_failure: always
